#!/usr/bin/env python

import sys

# nth term, e.g. 'n + 1'
nth_term_exp = sys.argv[1]

# create funciton from the nth term expression
nth_term = eval('lambda n: ' + nth_term_exp, { '__builtins__': None })

# number of terms to print, e.g 10
N = int(sys.argv[2])

print "The first", N, "terms of the sequence '" + nth_term_exp + "' are:"

for i in range(N):
    n = i + 1
    print n, " -> ", nth_term(n)
